{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "static-site.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "static-site.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.tls.autoGenerate }}
    traefik.ingress.kubernetes.io/router.tls.certresolver: "letsencrypt"
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- $envValues := index .Values.environments .Values.currentEnvironment }}
    {{- range $envValues.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "static-site.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
  {{- if or $envValues.ingress.tls .Values.tls.autoGenerate }}
  tls:
    {{- if not .Values.tls.autoGenerate }}
    {{- toYaml $envValues.ingress.tls | nindent 4 }}
    {{- else }}
    - hosts:
        {{- range $envValues.ingress.hosts }}
        - {{ .host }}
        {{- end }}
      secretName: {{ include "static-site.fullname" $ }}-tls-{{ $.Values.currentEnvironment }}
    {{- end }}
  {{- end }}
{{- end }}