apiVersion: v1
kind: Secret
metadata:
  name: {{ include "static-site.fullname" . }}
type: Opaque
data:
{{- range $key, $val := index .Values.environments .Values.currentEnvironment "environment" }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}