{{- if .Values.tls.useSelfSigned }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.secretName }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.certificate | b64enc | quote }}
  tls.key: {{ .Values.tls.privateKey | b64enc | quote }}
{{- end }}
