{{- $envValues := index .Values.environments .Values.currentEnvironment -}}
{{- $secretName := include "static-site.fullname" . | printf "%s-tls-%s" .Values.currentEnvironment -}}

{{- if and (not .Values.tls.autoGenerate) .Values.tls.certificate .Values.tls.privateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.certificate | b64enc | quote }}
  tls.key: {{ .Values.tls.privateKey | b64enc | quote }}
{{- end }}
